# Use an official Node.js 14 image as a base
FROM node:latest

# Set the working directory to /app
WORKDIR /Fashionstore

# Copy the package*.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Next.js application
RUN npm run build

# Expose the port the app will run on
EXPOSE 3000

# Run the command to start the development server
CMD ["npm", "run", "start"]